apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: paper-metrics
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - paper
  selector:
    matchLabels:
      app: paper
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics